### ISSUE TITLE
Possible to dual-license with GPL?

### ISSUE THREAD

**Issue by DrMcCoy** [flibitijibibo/FACT#1]
Hej!

This library is probably of interest to me for https://github.com/xoreos/xoreos (specifically, because of Jade Empire). I'd probably prefer to pull the code into xoreos, especially since the Windows version of Jade Empire uses an ASCII variant of the XACT formats (which as far as I understand is not usual?), so I'd probably have to fiddle with the code anyway in a way that's possibly not relevant to you.

Unfortunately, the Ms-PL doesn't seem to be compatible with the GPL. According to [this StackExchange answer](https://softwareengineering.stackexchange.com/a/191138), the issue seems to be 3. (D).

Would it be possible to dual-license this library Ms-PL and GPL (well, xoreos is GPLv3+, so either GPLv2+ or GPLv3+ would be fine with me)?

Cheers
Sven

**Comment by flibitijibibo** [comment]
I suppose we could relicense under GPLv2 based on unxwb's original license rather than the permissive license that the MonoGame project got for us, but you're going to have to ask all the other contributors first.

My advice: See if FACT even does what Jade Empire wants, then figure out the licensing once you know the hunt will be worth it.

(If it were up to me this whole thing would be under zlib, but I doubt I'm going to write this entirely from scratch, so I just went with Ms-PL again...)

**Comment by DrMcCoy** [comment]
> but you're going to have to ask all the other contributors first

Ah, so there are other contributors other than yourself. Yeah, that makes it a lot of work. :/

> See if FACT even does what Jade Empire wants, then figure out the licensing once you know the hunt will be worth it.

Sounds like good advice, yes, thanks.

I'll close this issue then, until I even know if it actually is relevant for xoreos. :)
I'll comment here with my findings then.

If it is, that'll be some fun hunting I'm going to have, I guess.

> but I doubt I'm going to write this entirely from scratch, so I just went with Ms-PL again

Of course, makes sense.
